# Generated by Django 5.2.6 on 2026-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Envio de checklist',
                'verbose_name_plural': 'Envios de checklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
