# Generated by Django 5.2.6 on 2026-09-24 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_checklistdigestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_label', models.CharField(max_length=420)),
                ('user_label', models.CharField(max_length=254)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='questions.rulecard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alteração de card',
                'verbose_name_plural': 'Alterações de card',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
