# Generated by Django 5.2.6 on 2025-10-08 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pergunta')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('reviewed', 'Revisado')], default='new', max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('processo', 'Processo'), ('seguranca', 'Segurança'), ('comunicacao', 'Comunicação'), ('juridico', 'Jurídico'), ('operacional', 'Operacional'), ('outros', 'Outros')], default='outros', max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AskedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(db_index=True, default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pergunta sem resultado',
                'verbose_name_plural': 'Perguntas sem resultado',
                'ordering': ['-count', 'term'],
                'indexes': [models.Index(fields=['count'], name='questions_a_count_a19358_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RuleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do card (opcional).', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='questions.rule')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['rule', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Busca sem resultado',
                'verbose_name_plural': 'Buscas sem resultado',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['term', 'created_at'], name='questions_s_term_35b520_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='questions.rulecard')),
                ('tags', models.ManyToManyField(blank=True, related_name='bullets', to='questions.tag')),
            ],
            options={
                'verbose_name': 'Bullet',
                'verbose_name_plural': 'Bullets',
                'ordering': ['card', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['slug'], name='questions_r_slug_f1819b_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_published', 'order'], name='questions_r_is_publ_7e5d55_idx'),
        ),
    ]
