# Generated by Django 4.2.24 on 2025-09-24 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pergunta')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('reviewed', 'Revisado')], default='new', max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
