# Generated by Django 4.2.24 on 2025-09-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuleBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Bullet',
                'verbose_name_plural': 'Bullets',
                'ordering': ['card', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do card (opcional).', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['rule', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('processo', 'Processo'), ('seguranca', 'Segurança'), ('comunicacao', 'Comunicação'), ('juridico', 'Jurídico'), ('operacional', 'Operacional'), ('outros', 'Outros')], default='outros', max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterField(
            model_name='rule',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['slug'], name='questions_r_slug_f1819b_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_published', 'order'], name='questions_r_is_publ_7e5d55_idx'),
        ),
        migrations.AddField(
            model_name='rulecard',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='questions.rule'),
        ),
        migrations.AddField(
            model_name='rulebullet',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='questions.rulecard'),
        ),
        migrations.AddField(
            model_name='rulebullet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bullets', to='questions.tag'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category'),
        ),
    ]
