# Generated by Django 5.2.6 on 2026-01-17 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_checklistsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDigestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('slot', models.CharField(db_index=True, max_length=32)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='success', max_length=16)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Envio de digest (Telegram)',
                'verbose_name_plural': 'Envios de digest (Telegram)',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot'), name='uniq_digest_date_slot')],
            },
        ),
    ]
