# Generated by Django 4.2.24 on 2025-09-27 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_fulltext_mariadb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Busca sem resultado',
                'verbose_name_plural': 'Buscas sem resultado',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['term', 'created_at'], name='questions_s_term_35b520_idx')],
            },
        ),
    ]
