# Generated by Django 4.2.24 on 2025-09-27 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_searchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(db_index=True, default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pergunta sem resultado',
                'verbose_name_plural': 'Perguntas sem resultado',
                'ordering': ['-count', 'term'],
                'indexes': [models.Index(fields=['count'], name='questions_a_count_a19358_idx')],
            },
        ),
    ]
