# Generated by Django 5.2.6 on 2025-10-08 21:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Faculdade')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Modalidade')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Colocação')),
                ('points', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scoreboard.faculty')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scoreboard.modality')),
            ],
            options={
                'ordering': ['modality', 'position'],
                'unique_together': {('modality', 'position')},
            },
        ),
    ]
